name=I2CIP-LCD-MCP23008
version=0.1
author=Jayden Lefebvre <jayden.lefebvre@peapodtech.com>
maintainer=Jayden Lefebvre <jayden.lefebvre@peapodtech.com>
sentence=A library of protocols for interfacing with I2C devices on a modular switched network.
paragraph=See README for compatible hardware specifications. State management for plug-and-play compatibility. Tested on Arduino Nano.
category=Communication
url=https://github.com/PeaPodTechnologies/I2CIP-LCD-MCP23008/
architectures=avr
includes=LCD-MCP23008.h